name: Build and Push Docker Images

on:
  push:
    branches:
      - main  

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    outputs:
      frontend_commit_id: ${{ steps.build-frontend.outputs.GIT_COMMIT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        id: build-frontend
        run: |
          cd frontend
          npm install
          npm run build
          GIT_COMMIT_ID=$(git rev-parse --short HEAD)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${GIT_COMMIT_ID}  .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${GIT_COMMIT_ID}
          echo "GIT_COMMIT_ID=${GIT_COMMIT_ID}" >> $GITHUB_ENV
          echo "::set-output name=GIT_COMMIT_ID::${GIT_COMMIT_ID}"

  build-backend:
    runs-on: ubuntu-latest
    outputs:
      backend_commit_id: ${{ steps.build-backend.outputs.GIT_COMMIT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        id: build-backend
        run: |
          cd backend
          npm install
          GIT_COMMIT_ID=$(git rev-parse --short HEAD)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${GIT_COMMIT_ID}  .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:${GIT_COMMIT_ID}
          echo "GIT_COMMIT_ID=${GIT_COMMIT_ID}" >> $GITHUB_ENV
          echo "::set-output name=GIT_COMMIT_ID::${GIT_COMMIT_ID}"

  trigger-update-values-pipeline:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    steps:
      - name: Trigger workflow in Helm repository to update values.yaml
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: Fenleap/Fenwave-test  
          workflow: update-helm-values.yml
          ref: main  
          inputs:
            frontend_tag: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ needs.build-frontend.outputs.frontend_commit_id }}
            backend_tag: ${{ secrets.DOCKER_USERNAME }}/backend:${{ needs.build-backend.outputs.backend_commit_id }}
